### ISSUE TITLE
Problema con el despliegue en local

### ISSUE THREAD

**Issue by SiiNerGia** [CavernaryBeast/Decide-Dialga-auth#5]
Al lanzar el proyecto en local con las dependencias de requirements.txt, permite entrar a localhost:8000 pero no a localhost:8000/admin

Al lanzar desde docker, permite entrar a localhost:8000/admin pero no a localhost:8000, ademas no deja iniciar una votacion.

El comportamiento esperado seria que no diese ningun error en esas situaciones.

**Comment by JaviToro** [comment]
Se soluciona el error haciendo un uso adecuado del archivo local_settings.py, en lugar de usar el settings genérico.

**Comment by SiiNerGia** [comment]
Resuelto, era un problema con el local settings.
